"""
Curated Indian FMCG, Staples, and Sports Supplements Knowledge Base.

Serves as high-precision secondary ground-truth data source when Open Food Facts
lacks data or has missing macronutrient fields.
"""

import difflib
import re
import urllib.parse

CURATED_FOOD_DATABASE = [
    # -------------------------------------------------------------
    # 1. NOODLES, PASTA & STAPLES
    # -------------------------------------------------------------
    {
        "id": "maggi_masala_noodles",
        "name": "Maggi 2-Minute Masala Instant Noodles",
        "brand": "Nestle Maggi",
        "code": "8901058852233",
        "image_url": "https://images.openfoodfacts.org/images/products/890/105/885/2233/front_en.11.400.jpg",
        "categories": "Plant-based foods, Noodles, Instant noodles, Wheat noodles",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Refined wheat flour (Maida), Palm oil, Salt, Wheat gluten, Mineral (Calcium carbonate), Thickener (508), Acidity regulators (501(i), 500(i)), Humectant (451(i)). Hydrolysed groundnut protein, Mixed spices (23.6%), Noodle powder, Sugar, Flavour enhancer (635).",
        "sugars_100g": 3.2,
        "fat_100g": 15.7,
        "saturated_fat_100g": 6.8,
        "proteins_100g": 8.0,
        "fiber_100g": 3.6,
        "energy_kcal_100g": 427,
        "additives_count": 6,
        "nutriscore_grade": "d",
        "labels": "source of iron, calcium",
        "known_claims": ["goodness of iron", "quick 2-minute meal", "tasty masala"],
        "keywords": ["maggi", "masala noodles", "instant noodles", "maggi noodles", "nestle maggi", "2 minute noodles"],
        "price_inr": 48,
        "price_usd": 0.89,
    },
    {
        "id": "maggi_chicken_noodles",
        "name": "Maggi 2-Minute Special Chicken Instant Noodles",
        "brand": "Nestle Maggi",
        "code": "8901058852288",
        "image_url": "",
        "categories": "Plant-based foods, Noodles, Instant noodles, Chicken noodles, Wheat noodles",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Refined wheat flour (Maida), Palm oil, Salt, Wheat gluten, Mineral (Calcium carbonate), Thickener (508), Acidity regulators (501(i), 500(i)). Chicken Tastemaker: Chicken meat powder (15%), Mixed spices, Sugar, Onion powder, Flavour enhancer (635), Garlic powder.",
        "sugars_100g": 1.1,
        "fat_100g": 15.2,
        "saturated_fat_100g": 6.8,
        "proteins_100g": 8.8,
        "fiber_100g": 3.2,
        "energy_kcal_100g": 432,
        "additives_count": 5,
        "nutriscore_grade": "d",
        "labels": "chicken flavor, quick meal",
        "known_claims": ["real chicken aroma", "quick 2-minute meal", "delicious chicken flavour"],
        "keywords": ["maggi chicken", "maggi chicken noodles", "maggie chicken noodles", "maggie chicken", "nestle maggi chicken", "maggi special chicken noodles"],
        "price_inr": 25,
        "price_usd": 0.49,
    },
    {
        "id": "maggi_veg_atta_noodles",
        "name": "Maggi Nutri-licious Masala Veg Atta Noodles",
        "brand": "Nestle Maggi",
        "code": "8901058852349",
        "image_url": "https://images.openfoodfacts.org/images/products/890/105/885/2349/front_en.14.400.jpg",
        "categories": "Plant-based foods, Noodles, Instant noodles, Atta noodles",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Whole wheat flour (Atta) (85.3%), Palm oil, Iodised salt, Wheat gluten, Thickeners (508, 412), Acidity regulators (501(i), 500(i)). Masala Tastemaker: Dehydrated vegetables (18.6%) (Carrot, Green peas, Onion), Mixed spices, Sugar, Hydrolysed peanut protein.",
        "sugars_100g": 2.2,
        "fat_100g": 12.5,
        "saturated_fat_100g": 5.4,
        "proteins_100g": 9.8,
        "fiber_100g": 6.8,
        "energy_kcal_100g": 410,
        "additives_count": 4,
        "nutriscore_grade": "c",
        "labels": "high fibre, whole wheat atta",
        "known_claims": ["goodness of whole wheat atta", "high fibre", "with real veggies"],
        "keywords": ["masala veg atta noodles", "veg atta noodles", "atta noodles", "maggi atta", "maggi veg atta noodles"],
        "price_inr": 110,
        "price_usd": 1.69,
    },
    {
        "id": "slurrp_farm_millet_noodles",
        "name": "Slurrp Farm Foxtail Millet Hakka Noodles",
        "brand": "Slurrp Farm",
        "code": "8906123456789",
        "image_url": "https://images.openfoodfacts.org/images/products/890/612/345/6789/front_en.3.400.jpg",
        "categories": "Noodles, Millet noodles, Hakka noodles",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Foxtail millet flour, Little millet flour, Whole wheat flour, Cluster bean powder, Salt. Zero palm oil, not fried.",
        "sugars_100g": 0.5,
        "fat_100g": 1.2,
        "saturated_fat_100g": 0.3,
        "proteins_100g": 12.4,
        "fiber_100g": 9.8,
        "energy_kcal_100g": 360,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% natural, no preservatives, no maida, zero palm oil, not fried",
        "known_claims": ["100% natural", "no preservatives", "zero palm oil", "not fried", "high fibre", "no maida"],
        "keywords": ["slurrp farm noodles", "millet noodles", "foxtail millet noodles", "healthy noodles", "slurrp farm"],
        "price_inr": 99,
        "price_usd": 1.49,
    },
    {
        "id": "wickedgud_millet_noodles",
        "name": "WickedGud Masala Instant Millet Noodles",
        "brand": "WickedGud",
        "code": "8908012345678",
        "image_url": "https://images.openfoodfacts.org/images/products/890/801/234/5678/front_en.5.400.jpg",
        "categories": "Noodles, Millet noodles, Healthy noodles",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Multi-millet flour (Finger millet, Kodo millet, Barnyard millet), Whole wheat flour, Lentil protein, Rice bran oil, Spices, Salt.",
        "sugars_100g": 1.0,
        "fat_100g": 2.5,
        "saturated_fat_100g": 0.6,
        "proteins_100g": 14.0,
        "fiber_100g": 11.2,
        "energy_kcal_100g": 355,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% natural, high protein, high fibre, no palm oil, no maida",
        "known_claims": ["100% natural", "high protein", "high fibre", "no palm oil", "no maida", "no preservatives"],
        "keywords": ["wickedgud", "wickedgud noodles", "millet noodles masala", "healthy instant noodles"],
        "price_inr": 85,
        "price_usd": 1.49,
    },
    {
        "id": "masterchow_ramen_noodles",
        "name": "MasterChow 100% Whole Wheat Ramen & Hakka Noodles",
        "brand": "MasterChow",
        "code": "8908019999012",
        "image_url": "https://images.openfoodfacts.org/images/products/890/801/999/9012/front_en.3.400.jpg",
        "categories": "Plant-based foods, Cereals, Noodles, Ramen, Whole wheat noodles",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Whole Wheat Flour (Atta), Cluster Bean Powder, Salt, Water. Not fried, zero maida, zero palm oil, zero preservatives.",
        "sugars_100g": 1.0,
        "fat_100g": 1.2,
        "saturated_fat_100g": 0.3,
        "proteins_100g": 11.5,
        "fiber_100g": 6.0,
        "energy_kcal_100g": 350,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% whole wheat, not fried, zero maida, zero palm oil, high protein",
        "known_claims": ["100% whole wheat", "not fried", "zero maida", "zero palm oil", "healthy ramen"],
        "keywords": ["ramen", "ramen noodles", "masterchow ramen", "wheat ramen", "instant ramen", "healthy ramen"],
        "price_inr": 125,
        "price_usd": 1.99,
    },
    {
        "id": "nissin_geki_korean_ramen",
        "name": "Nissin Geki Hot & Spicy Korean Veg Instant Ramen",
        "brand": "Nissin India",
        "code": "8901014002345",
        "image_url": "https://images.openfoodfacts.org/images/products/890/101/400/2345/front_en.7.400.jpg",
        "categories": "Plant-based foods, Cereals, Noodles, Ramen, Instant noodles, Spicy ramen",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Wheat Flour, Palm Oil, Salt, Wheat Gluten, Spices and Condiments (Chilli, Garlic, Onion), Flavour Enhancers (INS 627, INS 631).",
        "sugars_100g": 3.5,
        "fat_100g": 17.5,
        "saturated_fat_100g": 8.5,
        "proteins_100g": 8.5,
        "fiber_100g": 3.0,
        "energy_kcal_100g": 465,
        "additives_count": 4,
        "nutriscore_grade": "d",
        "labels": "korean style ramen, hot and spicy, veg",
        "known_claims": ["korean style spicy ramen", "fiery spice", "rich flavour"],
        "keywords": ["nissin geki", "nissin ramen", "korean ramen", "geki ramen", "spicy ramen"],
        "price_inr": 50,
        "price_usd": 0.89,
    },
    {
        "id": "nongshim_shin_ramyun_veg",
        "name": "Nongshim Shin Ramyun Gourmet Spicy Veg Ramen",
        "brand": "Nongshim",
        "code": "8801043014854",
        "image_url": "https://images.openfoodfacts.org/images/products/880/104/301/4854/front_en.11.400.jpg",
        "categories": "Plant-based foods, Cereals, Noodles, Ramen, Korean noodles",
        "countries": "India, South Korea",
        "is_available_in_india": True,
        "ingredients_text": "Wheat Flour, Palm Oil, Potato Starch, Salt, Dried Vegetables (Mushroom, Bok Choy, Carrot, Red Pepper), Spices.",
        "sugars_100g": 3.0,
        "fat_100g": 14.0,
        "saturated_fat_100g": 6.8,
        "proteins_100g": 9.0,
        "fiber_100g": 3.5,
        "energy_kcal_100g": 430,
        "additives_count": 3,
        "nutriscore_grade": "c",
        "labels": "gourmet spicy, 100% vegetarian, authentic korean ramen",
        "known_claims": ["gourmet spicy", "authentic ramyun broth", "100% vegetarian"],
        "keywords": ["shin ramyun", "nongshim ramen", "nongshim shin ramyun", "korean ramen", "ramen"],
        "price_inr": 140,
        "price_usd": 1.99,
    },
    {
        "id": "wai_wai_whole_wheat_ramen",
        "name": "Wai Wai 100% Whole Wheat Ready-to-Eat Instant Ramen",
        "brand": "Wai Wai",
        "code": "8906007010123",
        "image_url": "https://images.openfoodfacts.org/images/products/890/600/701/0123/front_en.4.400.jpg",
        "categories": "Plant-based foods, Cereals, Noodles, Ramen, Ready-to-eat noodles",
        "countries": "India, Nepal",
        "is_available_in_india": True,
        "ingredients_text": "Whole Wheat Flour (Atta 75%), Edible Vegetable Oil, Salt, Spices, Hydrolysed Plant Protein.",
        "sugars_100g": 2.0,
        "fat_100g": 14.5,
        "saturated_fat_100g": 6.5,
        "proteins_100g": 9.5,
        "fiber_100g": 5.0,
        "energy_kcal_100g": 435,
        "additives_count": 2,
        "nutriscore_grade": "c",
        "labels": "made with 100% whole wheat atta, rich in fibre",
        "known_claims": ["made with 100% atta", "munch it soup it", "source of protein and fibre"],
        "keywords": ["wai wai ramen", "wai wai noodles", "wai wai", "instant ramen", "wai wai atta"],
        "price_inr": 35,
        "price_usd": 0.69,
    },

    # -------------------------------------------------------------
    # 2. PROTEIN & SPORTS SUPPLEMENTS
    # -------------------------------------------------------------
    {
        "id": "muscleblaze_biozyme_whey",
        "name": "MuscleBlaze Biozyme Performance Whey Protein",
        "brand": "MuscleBlaze",
        "code": "8906067026543",
        "image_url": "https://images.openfoodfacts.org/images/products/890/606/702/6543/front_en.7.400.jpg",
        "categories": "Dietary supplements, Bodybuilding supplements, Protein powders, Whey protein",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Whey Protein Concentrate (89.5%), Cocoa Powder, Enhanced Absorption Formula (EAF) (Enzyme Blend), Stabilizer (INS 415), Sodium Chloride, Sweetener (INS 955), Anticaking agent (INS 551).",
        "sugars_100g": 4.5,
        "fat_100g": 5.2,
        "saturated_fat_100g": 3.1,
        "proteins_100g": 70.0,
        "fiber_100g": 1.5,
        "energy_kcal_100g": 395,
        "additives_count": 3,
        "nutriscore_grade": "a",
        "labels": "high protein, low sugar, clinically tested",
        "known_claims": ["high protein", "enhanced absorption", "50% higher protein absorption", "low carb"],
        "keywords": ["muscleblaze biozyme whey", "biozyme whey", "muscleblaze whey", "muscleblaze", "biozyme performance whey"],
        "price_inr": 2399,
        "price_usd": 32.00,
    },
    {
        "id": "on_gold_standard_whey",
        "name": "Optimum Nutrition (ON) Gold Standard 100% Whey Isolate",
        "brand": "Optimum Nutrition",
        "code": "748927028669",
        "image_url": "https://images.openfoodfacts.org/images/products/007/489/270/28669/front_en.12.400.jpg",
        "categories": "Dietary supplements, Protein powders, Whey protein isolate",
        "countries": "India, United States",
        "is_available_in_india": True,
        "ingredients_text": "Protein Blend (Whey Protein Isolates, Whey Protein Concentrate, Whey Peptides), Cocoa (Processed with Alkali), Natural and Artificial Flavors, Lecithin, Acesulfame Potassium, Aminogen, Lactase.",
        "sugars_100g": 3.3,
        "fat_100g": 3.3,
        "saturated_fat_100g": 1.6,
        "proteins_100g": 80.0,
        "fiber_100g": 1.0,
        "energy_kcal_100g": 390,
        "additives_count": 2,
        "nutriscore_grade": "a",
        "labels": "high protein, whey isolate, low sugar",
        "known_claims": ["high protein", "100% whey isolate primary source", "low sugar", "gluten-free"],
        "keywords": ["optimum nutrition gold standard whey", "on gold standard whey", "on whey", "gold standard 100% whey", "optimum nutrition"],
        "price_inr": 3199,
        "price_usd": 42.99,
    },
    {
        "id": "asitis_raw_whey_isolate",
        "name": "AS-IT-IS Nutrition 100% Pure Whey Protein Isolate (Unflavoured)",
        "brand": "AS-IT-IS Nutrition",
        "code": "8906095320019",
        "image_url": "https://images.openfoodfacts.org/images/products/890/609/532/0019/front_en.4.400.jpg",
        "categories": "Dietary supplements, Protein powders, Whey protein isolate, Pure protein",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "100% Pure Whey Protein Isolate. No additives, no flavours, no sweeteners, zero sugar, no preservatives.",
        "sugars_100g": 0.0,
        "fat_100g": 0.5,
        "saturated_fat_100g": 0.2,
        "proteins_100g": 90.0,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 370,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% natural, zero sugar, no preservatives, chemical-free, high protein",
        "known_claims": ["100% natural", "100% pure", "zero sugar", "no preservatives", "high protein", "chemical-free", "unflavoured"],
        "keywords": ["as it is raw whey", "as-it-is whey isolate", "asitis protein", "raw whey isolate", "pure whey"],
        "price_inr": 1899,
        "price_usd": 24.99,
    },
    {
        "id": "amul_high_protein_lassi",
        "name": "Amul High Protein Rose Lassi (15g Protein)",
        "brand": "Amul",
        "code": "8901262010191",
        "image_url": "https://images.openfoodfacts.org/images/products/890/126/201/0191/front_en.8.400.jpg",
        "categories": "Beverages, Milk, Fermented milk, High protein dairy, Lassi",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Pasteurised toned milk, Milk solids, Milk protein concentrate, Rose flavour, Active lactic cultures. No added sugar.",
        "sugars_100g": 2.5,
        "fat_100g": 0.8,
        "saturated_fat_100g": 0.5,
        "proteins_100g": 7.5,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 50,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "high protein, no added sugar, 100% natural, low fat",
        "known_claims": ["high protein", "no added sugar", "100% natural", "low fat", "15g protein per pack"],
        "keywords": ["amul high protein lassi", "amul protein lassi", "amul lassi", "amul protein", "high protein lassi"],
        "price_inr": 25,
        "price_usd": 0.35,
    },

    # -------------------------------------------------------------
    # 3. SPREADS & NUT BUTTERS
    # -------------------------------------------------------------
    {
        "id": "nutella_hazelnut_spread",
        "name": "Nutella Hazelnut Spread with Cocoa",
        "brand": "Ferrero Nutella",
        "code": "8000500179864",
        "image_url": "https://images.openfoodfacts.org/images/products/800/050/017/9864/front_en.118.400.jpg",
        "categories": "Spreads, Sweet spreads, Hazelnut spreads, Chocolate spreads",
        "countries": "India, France, United States",
        "is_available_in_india": True,
        "ingredients_text": "Sugar, Palm oil, Hazelnuts (13%), Skimmed milk powder (8.7%), Fat-reduced cocoa (7.4%), Emulsifier: lecithins (soya), Vanillin.",
        "sugars_100g": 56.3,
        "fat_100g": 30.9,
        "saturated_fat_100g": 10.6,
        "proteins_100g": 6.3,
        "fiber_100g": 3.0,
        "energy_kcal_100g": 539,
        "additives_count": 2,
        "nutriscore_grade": "e",
        "labels": "no artificial colours, no preservatives",
        "known_claims": ["start your day with nutella", "goodness of hazelnuts", "no artificial colours", "no preservatives"],
        "keywords": ["nutella", "nutella hazelnut spread", "chocolate spread", "ferrero nutella", "choco spread"],
        "price_inr": 390,
        "price_usd": 4.99,
    },
    {
        "id": "pintola_natural_peanut_butter",
        "name": "Pintola All Natural Peanut Butter (100% Roasted Peanuts)",
        "brand": "Pintola",
        "code": "8906076120010",
        "image_url": "https://images.openfoodfacts.org/images/products/890/607/612/0010/front_en.15.400.jpg",
        "categories": "Spreads, Nut butters, Peanut butter",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "100% Roasted Peanuts. Zero added sugar, zero hydrogenated oil, zero preservatives, zero salt.",
        "sugars_100g": 3.0,
        "fat_100g": 49.0,
        "saturated_fat_100g": 8.0,
        "proteins_100g": 30.0,
        "fiber_100g": 8.0,
        "energy_kcal_100g": 610,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% natural, no added sugar, zero sugar, high protein, no preservatives, vegan",
        "known_claims": ["100% natural", "no added sugar", "zero sugar", "high protein", "no preservatives", "vegan", "100% pure"],
        "keywords": ["pintola peanut butter", "pintola natural", "pintola all natural peanut butter", "natural peanut butter", "pintola"],
        "price_inr": 299,
        "price_usd": 3.99,
    },
    {
        "id": "the_whole_truth_hazelnut_spread",
        "name": "The Whole Truth Dark Chocolate Hazelnut Spread",
        "brand": "The Whole Truth",
        "code": "8908015555001",
        "image_url": "https://images.openfoodfacts.org/images/products/890/801/555/5001/front_en.3.400.jpg",
        "categories": "Spreads, Sweet spreads, Hazelnut spreads, Clean spreads",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Hazelnuts (50%), Raw Whole Dates, Cocoa powder, Cocoa butter. No refined sugar, no palm oil, no artificial sweeteners, zero preservatives.",
        "sugars_100g": 18.0,
        "fat_100g": 38.0,
        "saturated_fat_100g": 7.0,
        "proteins_100g": 12.5,
        "fiber_100g": 9.0,
        "energy_kcal_100g": 520,
        "additives_count": 0,
        "nutriscore_grade": "b",
        "labels": "100% natural, no added sugar, no palm oil, no preservatives, chemical-free",
        "known_claims": ["100% natural", "no added sugar", "no palm oil", "no preservatives", "chemical-free", "zero refined sugar"],
        "keywords": ["the whole truth hazelnut spread", "the whole truth spread", "dark chocolate hazelnut spread", "the whole truth"],
        "price_inr": 450,
        "price_usd": 5.99,
    },

    # -------------------------------------------------------------
    # 3B. PENNE & HEALTHY PASTAS
    # -------------------------------------------------------------
    {
        "id": "disano_durum_wheat_penne",
        "name": "Disano 100% Durum Wheat Penne Rigate Pasta",
        "brand": "Disano",
        "code": "8906050550012",
        "image_url": "https://images.openfoodfacts.org/images/products/890/605/055/0012/front_en.3.400.jpg",
        "categories": "Plant-based foods, Cereals, Pasta, Penne, Dry pasta, Durum wheat pasta",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "100% Durum Wheat Semolina. No artificial colors, zero trans fats, zero cholesterol, zero preservatives.",
        "sugars_100g": 1.5,
        "fat_100g": 1.2,
        "saturated_fat_100g": 0.2,
        "proteins_100g": 12.0,
        "fiber_100g": 6.0,
        "energy_kcal_100g": 355,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% durum wheat, high protein, high fibre, zero maida, zero cholesterol",
        "known_claims": ["100% durum wheat", "high protein", "high fibre", "zero maida", "healthy pasta"],
        "keywords": ["penne pasta", "penne", "pasta", "disano pasta", "disano penne", "durum wheat pasta"],
        "price_inr": 125,
        "price_usd": 2.49,
    },
    {
        "id": "slurrp_farm_millet_penne",
        "name": "Slurrp Farm 100% Whole Millet & Ragi Penne Pasta",
        "brand": "Slurrp Farm",
        "code": "8906123456888",
        "image_url": "https://images.openfoodfacts.org/images/products/890/612/345/6888/front_en.5.400.jpg",
        "categories": "Plant-based foods, Cereals, Pasta, Penne, Millet pasta, Gluten-free pasta",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Whole Millet Flour (Ragi, Little Millet, Jowar), Rice Flour. Not fried, zero maida, zero preservatives.",
        "sugars_100g": 1.2,
        "fat_100g": 1.0,
        "saturated_fat_100g": 0.2,
        "proteins_100g": 11.0,
        "fiber_100g": 8.5,
        "energy_kcal_100g": 348,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% millet, zero maida, gluten-free, high fibre",
        "known_claims": ["100% millet", "zero maida", "gluten-free", "high fibre", "no preservatives"],
        "keywords": ["penne pasta", "penne", "millet pasta", "slurrp farm pasta", "ragi penne", "healthy pasta"],
        "price_inr": 165,
        "price_usd": 2.99,
    },
    {
        "id": "borges_whole_wheat_penne",
        "name": "Borges 100% Whole Wheat Penne Rigate Pasta",
        "brand": "Borges",
        "code": "8410179012345",
        "image_url": "https://images.openfoodfacts.org/images/products/841/017/901/2345/front_en.8.400.jpg",
        "categories": "Plant-based foods, Cereals, Pasta, Penne, Whole wheat pasta",
        "countries": "India, Spain",
        "is_available_in_india": True,
        "ingredients_text": "100% Whole Durum Wheat Semolina. High fiber, zero preservatives.",
        "sugars_100g": 2.0,
        "fat_100g": 1.8,
        "saturated_fat_100g": 0.3,
        "proteins_100g": 13.0,
        "fiber_100g": 7.5,
        "energy_kcal_100g": 350,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% whole wheat, high fibre, low glycemic index",
        "known_claims": ["100% whole wheat", "high fibre", "low glycemic index", "zero maida"],
        "keywords": ["penne pasta", "penne", "borges pasta", "whole wheat penne", "pasta"],
        "price_inr": 195,
        "price_usd": 3.49,
    },
    {
        "id": "urban_platter_durum_penne",
        "name": "Urban Platter Durum Wheat Semolina Penne Rigate Pasta",
        "brand": "Urban Platter",
        "code": "8906081923456",
        "image_url": "https://images.openfoodfacts.org/images/products/890/608/192/3456/front_en.3.400.jpg",
        "categories": "Plant-based foods, Cereals, Pasta, Penne, Durum wheat pasta",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "100% Durum Wheat Semolina (Suji). Zero maida, zero preservatives, high protein.",
        "sugars_100g": 2.0,
        "fat_100g": 1.5,
        "saturated_fat_100g": 0.3,
        "proteins_100g": 13.0,
        "fiber_100g": 4.0,
        "energy_kcal_100g": 360,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% durum wheat, zero maida, high protein, no preservatives",
        "known_claims": ["100% durum wheat", "zero maida", "high protein", "no preservatives"],
        "keywords": ["urban platter pasta", "penne pasta", "penne", "durum wheat pasta", "urban platter"],
        "price_inr": 325,
        "price_usd": 4.49,
    },
    {
        "id": "rummo_penne_rigate_66",
        "name": "Rummo Penne Rigate No 66 Artisan Italian Pasta",
        "brand": "Rummo",
        "code": "8008343200661",
        "image_url": "https://images.openfoodfacts.org/images/products/800/834/320/0661/front_en.14.400.jpg",
        "categories": "Plant-based foods, Cereals, Pasta, Penne, Artisan pasta, Italian pasta",
        "countries": "Italy, France",
        "is_available_in_india": False,
        "ingredients_text": "Durum Wheat Semolina (Lenta Lavorazione). May contain traces of soy.",
        "sugars_100g": 2.5,
        "fat_100g": 1.6,
        "saturated_fat_100g": 0.3,
        "proteins_100g": 14.5,
        "fiber_100g": 3.1,
        "energy_kcal_100g": 356,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "artisan quality, lenta lavorazione, imported italian pasta",
        "known_claims": ["artisan quality", "lenta lavorazione method", "holds cooking perfectly"],
        "keywords": ["rummo pasta", "rummo penne", "rummo", "imported pasta", "italian pasta", "penne rigate no 66"],
        "price_inr": 520,
        "price_usd": 6.99,
    },

    # -------------------------------------------------------------
    # 4. ENERGY BARS & CEREALS
    # -------------------------------------------------------------
    {
        "id": "yogabar_protein_bar",
        "name": "Yogabar 20g Whey Protein Bar (Hazelnut Toffee)",
        "brand": "Yogabar",
        "code": "8906087541234",
        "image_url": "https://images.openfoodfacts.org/images/products/890/608/754/1234/front_en.6.400.jpg",
        "categories": "Snacks, Sweet snacks, Bars, Protein bars, Energy bars",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Whey protein isolate, Almonds, Hazelnuts, Prebiotic dietary fiber, Dates, Cocoa butter. Zero added sugar, zero artificial preservatives.",
        "sugars_100g": 6.0,
        "fat_100g": 14.0,
        "saturated_fat_100g": 3.5,
        "proteins_100g": 33.3,
        "fiber_100g": 15.0,
        "energy_kcal_100g": 380,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "high protein, high fibre, no added sugar, gluten-free, 100% natural",
        "known_claims": ["high protein", "high fibre", "no added sugar", "gluten-free", "100% natural", "20g protein"],
        "keywords": ["yogabar protein bar", "yogabar", "20g protein bar", "healthy protein bar", "energy bar"],
        "price_inr": 120,
        "price_usd": 1.60,
    },
    {
        "id": "true_elements_rolled_oats",
        "name": "True Elements 100% Whole Grain Rolled Oats",
        "brand": "True Elements",
        "code": "8906089012345",
        "image_url": "https://images.openfoodfacts.org/images/products/890/608/901/2345/front_en.9.400.jpg",
        "categories": "Plant-based foods, Cereals, Oats, Rolled oats, Breakfast cereals",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "100% Whole Grain Rolled Oats. Zero added sugar, zero preservatives, 100% natural.",
        "sugars_100g": 0.8,
        "fat_100g": 6.8,
        "saturated_fat_100g": 1.2,
        "proteins_100g": 13.5,
        "fiber_100g": 11.5,
        "energy_kcal_100g": 389,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% natural, high fibre, no added sugar, zero sugar, high protein, no preservatives",
        "known_claims": ["100% natural", "high fibre", "no added sugar", "zero sugar", "high protein", "no preservatives", "heart healthy"],
        "keywords": ["true elements rolled oats", "true elements oats", "rolled oats", "whole grain oats", "true elements"],
        "price_inr": 249,
        "price_usd": 3.99,
    },
    {
        "id": "yogabar_dark_chocolate_muesli",
        "name": "Yogabar Dark Chocolate + Peanut Butter Crunch Muesli & Cereal",
        "brand": "Yogabar",
        "code": "8906087541999",
        "image_url": "https://images.openfoodfacts.org/images/products/890/608/754/1999/front_en.5.400.jpg",
        "categories": "Plant-based foods, Cereals, Muesli, Breakfast cereals, Chocolate cereals, Granola",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Rolled Oats (45%), Dark Chocolate (Cocoa Solids 70%), Whole Wheat Flakes, Peanut Butter, Quinoa Flakes, Pumpkin Seeds, Almonds. Zero refined white sugar, sweetened with jaggery and dates.",
        "sugars_100g": 5.2,
        "fat_100g": 12.0,
        "saturated_fat_100g": 3.0,
        "proteins_100g": 16.0,
        "fiber_100g": 8.5,
        "energy_kcal_100g": 415,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "70% dark chocolate, high protein, high fibre, zero refined sugar, 100% whole grain",
        "known_claims": ["70% dark chocolate", "high protein", "high fibre", "zero refined sugar", "100% whole grain", "no palm oil"],
        "keywords": ["chocolate cereal", "chocolate cerial", "dark chocolate cereal", "chocolate muesli", "yogabar chocolate", "chocos", "cocoa cereal"],
        "price_inr": 349,
        "price_usd": 4.99,
    },
    {
        "id": "slurrp_farm_ragi_chocolate_cereal",
        "name": "Slurrp Farm Ragi Chocolate Stars Breakfast Cereal",
        "brand": "Slurrp Farm",
        "code": "8906123456900",
        "image_url": "https://images.openfoodfacts.org/images/products/890/612/345/6900/front_en.7.400.jpg",
        "categories": "Plant-based foods, Cereals, Breakfast cereals, Chocolate cereals, Millet cereals",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Finger Millet (Ragi), Little Millet, Jowar, Natural Cocoa Powder (12%), Raw Unrefined Sugar, Rice, Salt. Not fried, zero maida, zero artificial preservatives.",
        "sugars_100g": 8.5,
        "fat_100g": 4.2,
        "saturated_fat_100g": 1.1,
        "proteins_100g": 8.0,
        "fiber_100g": 7.2,
        "energy_kcal_100g": 370,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% whole millet, zero maida, 3x calcium of milk, no artificial colors",
        "known_claims": ["100% whole millet", "zero maida", "goodness of ragi", "natural cocoa", "no palm oil"],
        "keywords": ["chocolate cereal", "chocolate cerial", "ragi chocolate cereal", "slurrp farm chocolate", "chocos", "healthy chocos"],
        "price_inr": 225,
        "price_usd": 3.49,
    },
    {
        "id": "kelloggs_chocos_cereal",
        "name": "Kellogg's Chocos Moons & Stars Chocolate Cereal",
        "brand": "Kellogg's",
        "code": "8901499008001",
        "image_url": "https://images.openfoodfacts.org/images/products/890/149/900/8001/front_en.11.400.jpg",
        "categories": "Plant-based foods, Cereals, Breakfast cereals, Chocolate cereals",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Wheat Solids (54.2%) (Whole Wheat Flour 29.6%, Wheat Flour 24.6%), Sugar, Cocoa Solids (5.4%), Edible Vegetable Oil (Palmolein), Mineral, Cereal Extract, Color (INS 150d), Artificial Chocolate Flavour.",
        "sugars_100g": 28.5,
        "fat_100g": 3.0,
        "saturated_fat_100g": 1.2,
        "proteins_100g": 6.8,
        "fiber_100g": 3.5,
        "energy_kcal_100g": 384,
        "additives_count": 4,
        "nutriscore_grade": "d",
        "labels": "source of iron, vitamins, made with whole wheat",
        "known_claims": ["made with whole grain", "goodness of iron and calcium", "chocolaty taste"],
        "keywords": ["kelloggs chocos", "chocos", "chocolate cereal", "chocolate cerial", "kelloggs chocolate"],
        "price_inr": 180,
        "price_usd": 2.99,
    },
    # -------------------------------------------------------------
    # 5. SOY SAUCES & HEALTHY CONDIMENTS
    # -------------------------------------------------------------
    {
        "id": "kikkoman_less_sodium_soy_sauce",
        "name": "Kikkoman Naturally Brewed Less Sodium Soy Sauce",
        "brand": "Kikkoman",
        "code": "041390001001",
        "image_url": "https://images.openfoodfacts.org/images/products/004/139/000/1001/front_en.12.400.jpg",
        "categories": "Condiments, Sauces, Soy sauces, Naturally brewed soy sauce",
        "countries": "India, Japan, United States",
        "is_available_in_india": True,
        "ingredients_text": "Water, Soybeans, Wheat, Salt, Lactic acid, Sodium benzoate. Naturally brewed with traditional koji fermentation.",
        "sugars_100g": 1.5,
        "fat_100g": 0.0,
        "saturated_fat_100g": 0.0,
        "proteins_100g": 9.2,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 65,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "naturally brewed, less sodium, preservative free, authentic fermentation",
        "known_claims": ["naturally brewed", "less sodium", "traditionally fermented", "rich umami taste"],
        "keywords": ["soy sauce", "soya sauce", "kikkoman soy sauce", "kikkoman", "less sodium soy sauce", "naturally brewed soy sauce", "dark soy sauce", "shoyu"],
        "price_inr": 280,
        "price_usd": 3.75,
    },
    {
        "id": "urban_platter_organic_shoyu",
        "name": "Urban Platter Organic Naturally Fermented Dark Soy Sauce (Shoyu)",
        "brand": "Urban Platter",
        "code": "8906081920011",
        "image_url": "https://images.openfoodfacts.org/images/products/890/608/192/0011/front_en.4.400.jpg",
        "categories": "Condiments, Sauces, Soy sauces, Organic soy sauce, Shoyu",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Organic Soybeans, Organic Wheat, Water, Natural Sea Salt. 100% naturally fermented in wooden barrels.",
        "sugars_100g": 1.0,
        "fat_100g": 0.0,
        "saturated_fat_100g": 0.0,
        "proteins_100g": 10.0,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 68,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% organic, naturally fermented, zero additives, chemical free, pure shoyu",
        "known_claims": ["100% organic", "naturally fermented", "no added caramel color", "zero chemical additives"],
        "keywords": ["urban platter soy sauce", "organic soy sauce", "dark soy sauce", "shoyu", "fermented soy sauce", "soy sauce", "soya sauce"],
        "price_inr": 395,
        "price_usd": 5.25,
    },
    {
        "id": "san_j_organic_tamari_soy_sauce",
        "name": "San-J Organic Gluten Free Tamari Soy Sauce (Reduced Sodium)",
        "brand": "San-J",
        "code": "075810001001",
        "image_url": "https://images.openfoodfacts.org/images/products/007/581/000/1001/front_en.8.400.jpg",
        "categories": "Condiments, Sauces, Soy sauces, Tamari, Gluten-free soy sauce",
        "countries": "United States",
        "is_available_in_india": False,
        "ingredients_text": "Organic Soybeans, Water, Salt, Organic Alcohol. 100% whole soybean brew without wheat.",
        "sugars_100g": 0.0,
        "fat_100g": 0.0,
        "saturated_fat_100g": 0.0,
        "proteins_100g": 10.5,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 60,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "organic, gluten free, non gmo, reduced sodium, 100% whole soy",
        "known_claims": ["organic", "gluten free", "non gmo verified", "reduced sodium", "100% soy"],
        "keywords": ["tamari", "tamari soy sauce", "gluten free soy sauce", "san-j", "san-j tamari", "soy sauce", "soya sauce"],
        "price_inr": 450,
        "price_usd": 6.00,
    },
    {
        "id": "chings_dark_soy_sauce",
        "name": "Ching's Secret Dark Soy Sauce",
        "brand": "Ching's Secret",
        "code": "8901595851411",
        "image_url": "https://images.openfoodfacts.org/images/products/890/159/585/1411/front_en.10.400.jpg",
        "categories": "Condiments, Sauces, Soy sauces, Dark soy sauce",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Water, Sugar, Soybeans (15%), Salt, Caramel color (150c), Acidity regulator (260), Preservative (211).",
        "sugars_100g": 4.5,
        "fat_100g": 0.0,
        "saturated_fat_100g": 0.0,
        "proteins_100g": 3.0,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 110,
        "additives_count": 2,
        "nutriscore_grade": "c",
        "labels": "desi chinese, dark soy sauce",
        "known_claims": ["rich dark color", "desi chinese flavour"],
        "keywords": ["chings soy sauce", "chings secret", "chings dark soy sauce", "dark soy sauce", "soy sauce", "soya sauce"],
        "price_inr": 60,
        "price_usd": 0.99,
    },
    {
        "id": "urban_platter_balsamic_vinegar",
        "name": "Urban Platter Italian Balsamic Vinegar of Modena IGP (Oak Aged)",
        "brand": "Urban Platter",
        "code": "8906081921234",
        "image_url": "https://images.openfoodfacts.org/images/products/890/608/192/1234/front_en.5.400.jpg",
        "categories": "Condiments, Vinegars, Balsamic vinegars, Balsamic vinegar of Modena",
        "countries": "India, Italy",
        "is_available_in_india": True,
        "ingredients_text": "Wine Vinegar, Cooked Grape Must, Caramel Color (INS 150d). Aged in wooden barrels in Modena, Italy.",
        "sugars_100g": 14.0,
        "fat_100g": 0.0,
        "saturated_fat_100g": 0.0,
        "proteins_100g": 0.5,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 88,
        "additives_count": 1,
        "nutriscore_grade": "a",
        "labels": "authentic balsamic vinegar of modena, igp certified, oak aged",
        "known_claims": ["balsamic vinegar of modena", "igp certified", "oak barrel aged"],
        "keywords": ["balsamic vinegar", "balsamic vinegar of modena", "vinegar", "urban platter balsamic vinegar", "vinaigre balsamique", "aceto balsamico"],
        "price_inr": 395,
        "price_usd": 5.49,
    },
    {
        "id": "borges_balsamic_vinegar_india",
        "name": "Borges Balsamic Vinegar of Modena IGP",
        "brand": "Borges",
        "code": "8410179001234",
        "image_url": "https://images.openfoodfacts.org/images/products/841/017/900/1234/front_en.10.400.jpg",
        "categories": "Condiments, Vinegars, Balsamic vinegars, Balsamic vinegar of Modena",
        "countries": "India, Spain, Italy",
        "is_available_in_india": True,
        "ingredients_text": "Wine Vinegar, Concentrated Grape Must, Colour (Caramel E150d), Preservative (Potassium Metabisulphite). Marketed in India by Borges India Pvt Ltd.",
        "sugars_100g": 15.0,
        "fat_100g": 0.0,
        "saturated_fat_100g": 0.0,
        "proteins_100g": 0.5,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 90,
        "additives_count": 2,
        "nutriscore_grade": "a",
        "labels": "balsamic vinegar of modena, igp certified, fssai certified",
        "known_claims": ["balsamic vinegar of modena", "igp certified", "ideal for salads and dressings"],
        "keywords": ["balsamic vinegar", "borges balsamic vinegar", "balsamic vinegar of modena", "vinegar", "aceto balsamico"],
        "price_inr": 375,
        "price_usd": 4.99,
    },
    {
        "id": "sprig_balsamic_vinegar",
        "name": "Sprig Artisanal Balsamic Vinegar of Modena IGP",
        "brand": "Sprig",
        "code": "8906059630012",
        "image_url": "https://images.openfoodfacts.org/images/products/890/605/963/0012/front_en.5.400.jpg",
        "categories": "Condiments, Vinegars, Balsamic vinegars, Balsamic vinegar of Modena",
        "countries": "Italy",
        "is_available_in_india": False,
        "ingredients_text": "Cooked Grape Must, Wine Vinegar. Barrel aged in Modena, Italy.",
        "sugars_100g": 13.5,
        "fat_100g": 0.0,
        "saturated_fat_100g": 0.0,
        "proteins_100g": 0.6,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 85,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% natural, barrel aged, no added caramel, igp certified",
        "known_claims": ["100% natural", "barrel aged", "no added caramel", "balsamic vinegar of modena"],
        "keywords": ["balsamic vinegar", "sprig balsamic vinegar", "artisanal balsamic vinegar", "vinegar"],
        "price_inr": 399,
        "price_usd": 5.25,
    },
    {
        "id": "disano_apple_cider_vinegar",
        "name": "DiSano Organic Raw Apple Cider Vinegar with Mother",
        "brand": "DiSano",
        "code": "8906063001122",
        "image_url": "https://images.openfoodfacts.org/images/products/890/606/300/1122/front_en.5.400.jpg",
        "categories": "Condiments, Vinegars, Apple cider vinegars, Organic vinegars",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "100% Certified Organic Raw Apple Cider Vinegar with Mother of Vinegar. Raw, unfiltered, unpasteurized. FSSAI certified.",
        "sugars_100g": 0.0,
        "fat_100g": 0.0,
        "saturated_fat_100g": 0.0,
        "proteins_100g": 0.1,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 0,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% organic, raw unfiltered, with the mother, fssai certified, zero sugar",
        "known_claims": ["100% organic", "raw unfiltered", "with the mother", "zero sugar", "gluten free"],
        "keywords": ["apple cider vinegar", "disano apple cider vinegar", "disano acv", "organic vinegar", "vinegar"],
        "price_inr": 199,
        "price_usd": 2.69,
    },
    {
        "id": "bragg_apple_cider_vinegar",
        "name": "Bragg Organic Raw Unfiltered Apple Cider Vinegar with Mother",
        "brand": "Bragg",
        "code": "074305001161",
        "image_url": "https://images.openfoodfacts.org/images/products/007/430/500/1161/front_en.12.400.jpg",
        "categories": "Condiments, Vinegars, Apple cider vinegars, Organic vinegars",
        "countries": "India, United States",
        "is_available_in_india": True,
        "ingredients_text": "Certified Organic Raw Apple Cider Vinegar, Purified Water. Diluted to 5% acidity. Unpasteurized with the 'Mother'.",
        "sugars_100g": 0.0,
        "fat_100g": 0.0,
        "saturated_fat_100g": 0.0,
        "proteins_100g": 0.0,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 0,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% organic, raw unfiltered, with the mother, non-gmo, zero sugar",
        "known_claims": ["100% organic", "raw unfiltered", "with the mother", "zero sugar", "gluten free"],
        "keywords": ["apple cider vinegar", "bragg apple cider vinegar", "acv", "organic vinegar", "vinegar"],
        "price_inr": 620,
        "price_usd": 7.99,
    },

    # -------------------------------------------------------------
    # 7. HEALTHY SNACKS, MAKHANA & SEEDS
    # -------------------------------------------------------------
    {
        "id": "farmley_roasted_peri_peri_makhana",
        "name": "Farmley Roasted Peri Peri Makhana (Fox Nuts)",
        "brand": "Farmley",
        "code": "8908018881234",
        "image_url": "https://images.openfoodfacts.org/images/products/890/801/888/1234/front_en.3.400.jpg",
        "categories": "Snacks, Salty snacks, Makhana, Roasted fox nuts, Healthy snacks",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Fox Nuts (Makhana 80%), Olive Oil, Spices and Condiments (Peri Peri Chilli, Garlic, Onion, Black Pepper), Rock Salt. Roasted, not fried, zero palm oil.",
        "sugars_100g": 1.0,
        "fat_100g": 7.5,
        "saturated_fat_100g": 1.2,
        "proteins_100g": 9.5,
        "fiber_100g": 14.0,
        "energy_kcal_100g": 390,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "roasted not fried, zero palm oil, high protein, high fibre, gluten-free",
        "known_claims": ["roasted not fried", "zero palm oil", "high protein", "high fibre", "gluten free"],
        "keywords": ["makhana", "fox nuts", "roasted makhana", "farmley makhana", "peri peri makhana", "healthy snack"],
        "price_inr": 140,
        "price_usd": 2.20,
    },
    {
        "id": "true_elements_super_seeds_mix",
        "name": "True Elements 7 in 1 Super Seeds & Nut Mix",
        "brand": "True Elements",
        "code": "8906089019999",
        "image_url": "https://images.openfoodfacts.org/images/products/890/608/901/9999/front_en.5.400.jpg",
        "categories": "Snacks, Seeds, Roasted seeds, Healthy snacks",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Pumpkin Seeds, Watermelon Seeds, Chia Seeds, Flax Seeds, Sunflower Seeds, Sesame Seeds, Soy Nuts. Lightly roasted with rock salt.",
        "sugars_100g": 2.0,
        "fat_100g": 38.0,
        "saturated_fat_100g": 6.5,
        "proteins_100g": 24.5,
        "fiber_100g": 18.0,
        "energy_kcal_100g": 520,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% natural, high protein, rich in omega 3, zero added sugar, roasted",
        "known_claims": ["100% natural", "high protein", "rich in omega 3", "zero sugar", "100% raw roasted"],
        "keywords": ["seeds mix", "super seeds", "roasted seeds", "pumpkin seeds", "chia seeds", "flax seeds", "healthy snacks"],
        "price_inr": 225,
        "price_usd": 3.49,
    },

    # -------------------------------------------------------------
    # 8. BISCUITS & WHOLE GRAIN COOKIES
    # -------------------------------------------------------------
    {
        "id": "britannia_nutrichoice_digestive",
        "name": "Britannia NutriChoice Digestive 100% Atta Biscuits",
        "brand": "Britannia",
        "code": "8901063012345",
        "image_url": "https://images.openfoodfacts.org/images/products/890/106/301/2345/front_en.6.400.jpg",
        "categories": "Snacks, Sweet snacks, Biscuits, Digestive biscuits",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Wheat Flour (Atta 55%), Refined Palm Oil, Sugar (14.5%), Wheat Bran (4.5%), Invert Sugar Syrup, Leavening Agents (INS 503ii, INS 500ii), Salt, Emulsifier (INS 322).",
        "sugars_100g": 14.5,
        "fat_100g": 18.0,
        "saturated_fat_100g": 8.5,
        "proteins_100g": 8.0,
        "fiber_100g": 6.0,
        "energy_kcal_100g": 475,
        "additives_count": 3,
        "nutriscore_grade": "c",
        "labels": "100% atta, high fibre, digestive",
        "known_claims": ["100% atta", "high fibre", "goodness of wheat"],
        "keywords": ["digestive biscuits", "nutrichoice", "britannia digestive", "atta biscuits", "digestive"],
        "price_inr": 85,
        "price_usd": 1.25,
    },
    {
        "id": "early_foods_ragi_cookies",
        "name": "Early Foods Organic Sprouted Ragi & Cocoa Jaggery Cookies",
        "brand": "Early Foods",
        "code": "8908013334444",
        "image_url": "https://images.openfoodfacts.org/images/products/890/801/333/4444/front_en.4.400.jpg",
        "categories": "Snacks, Sweet snacks, Biscuits, Healthy cookies, Ragi biscuits",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Organic Sprouted Ragi Flour (35%), Whole Wheat Flour, Organic Jaggery (9%), Butter, Pure Cocoa Powder. Zero refined sugar, zero palm oil, zero baking powder/soda, zero preservatives.",
        "sugars_100g": 9.0,
        "fat_100g": 14.0,
        "saturated_fat_100g": 7.0,
        "proteins_100g": 8.5,
        "fiber_100g": 7.5,
        "energy_kcal_100g": 420,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% organic, no refined sugar, no palm oil, no preservatives, sprouted ragi",
        "known_claims": ["100% organic", "no refined sugar", "no palm oil", "no preservatives", "sprouted ragi goodness"],
        "keywords": ["ragi biscuits", "ragi cookies", "early foods", "healthy biscuits", "digestive biscuits", "digestive", "cookies"],
        "price_inr": 190,
        "price_usd": 2.99,
    },

    # -------------------------------------------------------------
    # 9. DARK CHOCOLATE & CLEAN TREATS
    # -------------------------------------------------------------
    {
        "id": "the_whole_truth_dark_chocolate",
        "name": "The Whole Truth 71% Single Origin Dark Chocolate (Dates Sweetened)",
        "brand": "The Whole Truth",
        "code": "8908015557777",
        "image_url": "https://images.openfoodfacts.org/images/products/890/801/555/7777/front_en.8.400.jpg",
        "categories": "Snacks, Sweet snacks, Chocolates, Dark chocolates",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Single Origin Cocoa Beans (55%), Cocoa Butter (16%), Raw Dates (29%). Zero added refined sugar, zero emulsifiers, zero artificial sweeteners.",
        "sugars_100g": 18.0,
        "fat_100g": 36.0,
        "saturated_fat_100g": 21.0,
        "proteins_100g": 9.0,
        "fiber_100g": 12.5,
        "energy_kcal_100g": 510,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "71% dark chocolate, no added sugar, zero emulsifiers, 100% clean",
        "known_claims": ["71% dark chocolate", "no added sugar", "sweetened only with dates", "zero emulsifiers"],
        "keywords": ["dark chocolate", "the whole truth chocolate", "clean chocolate", "sugar free chocolate", "cacao"],
        "price_inr": 225,
        "price_usd": 3.49,
    },
    {
        "id": "amul_dark_chocolate_75",
        "name": "Amul 75% Bitter Dark Chocolate",
        "brand": "Amul",
        "code": "8901262012019",
        "image_url": "https://images.openfoodfacts.org/images/products/890/126/201/2019/front_en.12.400.jpg",
        "categories": "Snacks, Sweet snacks, Chocolates, Dark chocolates",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Cocoa Solids (75%), Sugar (24%), Cocoa Butter, Permitted Emulsifier (E322, E476), Added Flavours.",
        "sugars_100g": 24.0,
        "fat_100g": 41.0,
        "saturated_fat_100g": 24.5,
        "proteins_100g": 8.5,
        "fiber_100g": 11.0,
        "energy_kcal_100g": 550,
        "additives_count": 2,
        "nutriscore_grade": "c",
        "labels": "75% cocoa, rich dark chocolate",
        "known_claims": ["75% rich cocoa", "dark chocolate goodness"],
        "keywords": ["amul dark chocolate", "amul chocolate", "dark chocolate", "75% dark chocolate", "amul"],
        "price_inr": 110,
        "price_usd": 1.75,
    },

    # -------------------------------------------------------------
    # 10. GREEN TEA & HERBAL INFUSIONS
    # -------------------------------------------------------------
    {
        "id": "organic_india_tulsi_green_tea",
        "name": "Organic India Tulsi Green Tea Classic (100% Certified Organic)",
        "brand": "Organic India",
        "code": "8901725181234",
        "image_url": "https://images.openfoodfacts.org/images/products/890/172/518/1234/front_en.9.400.jpg",
        "categories": "Beverages, Teas, Green teas, Herbal teas, Tulsi tea",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Rama Tulsi (Ocimum sanctum), Krishna Tulsi (Ocimum sanctum), Vana Tulsi (Ocimum gratissimum), Certified Organic Green Tea (Camellia sinensis). Zero sugar, zero calories, zero additives.",
        "sugars_100g": 0.0,
        "fat_100g": 0.0,
        "saturated_fat_100g": 0.0,
        "proteins_100g": 0.0,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 0,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% organic, rich in antioxidants, stress relieving, zero calories",
        "known_claims": ["100% organic", "rich in antioxidants", "boosts immunity", "stress relieving", "zero calories"],
        "keywords": ["green tea", "tulsi green tea", "organic india", "herbal tea", "organic green tea", "tea"],
        "price_inr": 195,
        "price_usd": 2.99,
    },

    # -------------------------------------------------------------
    # 11. DESI GHEE & COOKING OILS
    # -------------------------------------------------------------
    {
        "id": "anveshan_a2_cow_ghee",
        "name": "Anveshan A2 Vedic Desi Cow Bilona Ghee (100% Pure)",
        "brand": "Anveshan",
        "code": "8908016661111",
        "image_url": "https://images.openfoodfacts.org/images/products/890/801/666/1111/front_en.7.400.jpg",
        "categories": "Fats, Cooking fats, Ghee, Desi cow ghee, A2 ghee",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "100% Pure A2 Cow Milk Fat prepared using traditional Vedic Bilona method from Hallikar & Gir cows curd. Zero adulteration, zero preservatives.",
        "sugars_100g": 0.0,
        "fat_100g": 99.8,
        "saturated_fat_100g": 65.0,
        "proteins_100g": 0.0,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 898,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% pure a2 cow ghee, traditional bilona method, zero preservatives, lab tested",
        "known_claims": ["100% pure a2 cow ghee", "vedic bilona method", "zero preservatives", "lab tested pure"],
        "keywords": ["ghee", "a2 ghee", "desi cow ghee", "cow ghee", "anveshan ghee", "bilona ghee"],
        "price_inr": 899,
        "price_usd": 12.99,
    },
    {
        "id": "disano_extra_virgin_olive_oil",
        "name": "Disano 100% Extra Virgin Olive Oil (First Cold Pressed)",
        "brand": "Disano",
        "code": "8906063001234",
        "image_url": "https://images.openfoodfacts.org/images/products/890/606/300/1234/front_en.11.400.jpg",
        "categories": "Fats, Vegetable fats, Olive oils, Extra virgin olive oils, Cooking oils",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "100% Extra Virgin Olive Oil obtained directly from Spanish olives solely by mechanical means (First Cold Pressed). Zero chemical extraction.",
        "sugars_100g": 0.0,
        "fat_100g": 99.8,
        "saturated_fat_100g": 14.0,
        "proteins_100g": 0.0,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 900,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% extra virgin, first cold pressed, rich in mufa, zero cholesterol",
        "known_claims": ["100% extra virgin", "first cold pressed", "rich in mufa and antioxidants", "zero cholesterol"],
        "keywords": ["olive oil", "extra virgin olive oil", "evoo", "disano olive oil", "cooking oil", "cold pressed oil"],
        "price_inr": 649,
        "price_usd": 8.99,
    },

    # -------------------------------------------------------------
    # 12. HIGH PROTEIN DAIRY & PLANT MILK
    # -------------------------------------------------------------
    {
        "id": "amul_high_protein_lassi",
        "name": "Amul High Protein Rose Lassi (15g Protein)",
        "brand": "Amul",
        "code": "8901262078901",
        "image_url": "https://images.openfoodfacts.org/images/products/890/126/207/8901/front_en.5.400.jpg",
        "categories": "Beverages, Dairies, Fermented milk drinks, Lassi, High protein drinks",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Pasteurized Toned Milk, Milk Solids, Milk Protein Concentrate, Active Lactic Culture, Natural Rose Extract, Sucralose (INS 955).",
        "sugars_100g": 3.5,
        "fat_100g": 1.5,
        "saturated_fat_100g": 0.9,
        "proteins_100g": 7.5,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 58,
        "additives_count": 1,
        "nutriscore_grade": "a",
        "labels": "high protein, 15g protein per pack, low fat, no added sugar",
        "known_claims": ["15g protein per pack", "high protein", "low fat", "no added sugar"],
        "keywords": ["amul protein lassi", "high protein lassi", "amul high protein", "protein lassi", "lassi", "amul"],
        "price_inr": 25,
        "price_usd": 0.49,
    },
    {
        "id": "epigamia_greek_yogurt",
        "name": "Epigamia Natural High Protein Greek Yogurt",
        "brand": "Epigamia",
        "code": "8906079012345",
        "image_url": "https://images.openfoodfacts.org/images/products/890/607/901/2345/front_en.8.400.jpg",
        "categories": "Dairies, Fermented foods, Yogurts, Greek yogurts",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Pasteurized Double Toned Milk, Milk Solids, Live Active Cultures (S. thermophilus, L. bulgaricus). Zero added sugar, zero preservatives.",
        "sugars_100g": 3.5,
        "fat_100g": 3.0,
        "saturated_fat_100g": 1.8,
        "proteins_100g": 8.0,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 75,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "high protein, zero added sugar, no preservatives, authentic greek yogurt",
        "known_claims": ["high protein", "zero added sugar", "no preservatives", "probiotic rich"],
        "keywords": ["greek yogurt", "epigamia yogurt", "epigamia greek yogurt", "high protein curd", "yogurt", "curd"],
        "price_inr": 60,
        "price_usd": 0.99,
    },
    {
        "id": "urban_platter_almond_milk",
        "name": "Urban Platter Unsweetened Almond Milk (1L)",
        "brand": "Urban Platter",
        "code": "8906081928888",
        "image_url": "https://images.openfoodfacts.org/images/products/890/608/192/8888/front_en.6.400.jpg",
        "categories": "Beverages, Plant-based beverages, Almond milks, Plant milks",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Water, Almonds (4.5%), Calcium Carbonate, Sea Salt, Gellan Gum. Zero added sugar, lactose-free, dairy-free, vegan.",
        "sugars_100g": 0.2,
        "fat_100g": 1.8,
        "saturated_fat_100g": 0.2,
        "proteins_100g": 1.2,
        "fiber_100g": 0.6,
        "energy_kcal_100g": 24,
        "additives_count": 1,
        "nutriscore_grade": "a",
        "labels": "unsweetened, zero added sugar, dairy free, lactose free, vegan",
        "known_claims": ["unsweetened", "zero added sugar", "dairy free", "lactose free", "plant based"],
        "keywords": ["almond milk", "plant milk", "urban platter almond milk", "unsweetened milk", "vegan milk", "milk"],
        "price_inr": 280,
        "price_usd": 3.99,
    },

    # -------------------------------------------------------------
    # 13. CLEAN KETCHUP & CONDIMENTS
    # -------------------------------------------------------------
    {
        "id": "the_whole_truth_tomato_ketchup",
        "name": "The Whole Truth Clean Tomato Ketchup (Sweetened with Dates)",
        "brand": "The Whole Truth",
        "code": "8908015559999",
        "image_url": "https://images.openfoodfacts.org/images/products/890/801/555/9999/front_en.10.400.jpg",
        "categories": "Condiments, Sauces, Tomato sauces, Ketchup, Clean ketchup",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Fresh Tomatoes (75%), Raw Dates, Brewed Vinegar, Rock Salt, Spices. Zero added refined sugar, zero corn syrup, zero preservatives, zero artificial color.",
        "sugars_100g": 8.0,
        "fat_100g": 0.2,
        "saturated_fat_100g": 0.0,
        "proteins_100g": 1.8,
        "fiber_100g": 2.5,
        "energy_kcal_100g": 48,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "no refined sugar, sweetened only with dates, 100% clean, zero preservatives",
        "known_claims": ["no refined sugar", "sweetened only with dates", "100% clean", "zero preservatives", "real tomatoes"],
        "keywords": ["ketchup", "tomato ketchup", "the whole truth ketchup", "clean ketchup", "sauce", "tomato sauce"],
        "price_inr": 180,
        "price_usd": 2.60,
    },
    {
        "id": "kissan_fresh_tomato_ketchup",
        "name": "Kissan Fresh Tomato Ketchup",
        "brand": "Kissan",
        "code": "8901030012345",
        "image_url": "https://images.openfoodfacts.org/images/products/890/103/001/2345/front_en.4.400.jpg",
        "categories": "Condiments, Sauces, Tomato sauces, Ketchup",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Water, Tomato Paste (26%), Sugar (28%), Salt, Acidity Regulator (260), Thickeners (INS 1422, INS 415), Preservative (INS 211), Spices and Condiments.",
        "sugars_100g": 28.0,
        "fat_100g": 0.1,
        "saturated_fat_100g": 0.0,
        "proteins_100g": 1.2,
        "fiber_100g": 0.5,
        "energy_kcal_100g": 125,
        "additives_count": 4,
        "nutriscore_grade": "d",
        "labels": "100% real tomatoes, fresh tomato ketchup",
        "known_claims": ["100% real tomatoes", "deliciously tangy"],
        "keywords": ["kissan ketchup", "kissan tomato ketchup", "tomato ketchup", "ketchup", "sauce"],
        "price_inr": 120,
        "price_usd": 1.75,
    },

    # -------------------------------------------------------------
    # 14. HEALTH DRINKS & MALT POWDERS
    # -------------------------------------------------------------
    {
        "id": "gritzo_supermilk_teen_protein",
        "name": "Gritzo SuperMilk Clean Nutritional Protein Drink for Teens",
        "brand": "Gritzo",
        "code": "8906067029999",
        "image_url": "https://images.openfoodfacts.org/images/products/890/606/702/9999/front_en.7.400.jpg",
        "categories": "Beverages, Nutritional drinks, Health drinks, Protein drinks",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Whey Protein Concentrate (34%), Cocoa Powder, Calcium Caseinate, Unrefined Cane Sugar, DHA, Ashwagandha, 21 Essential Vitamins & Minerals. Zero maltodextrin, zero artificial flavours.",
        "sugars_100g": 4.5,
        "fat_100g": 3.5,
        "saturated_fat_100g": 1.8,
        "proteins_100g": 34.0,
        "fiber_100g": 4.5,
        "energy_kcal_100g": 375,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "clean protein, 100% natural, zero maltodextrin, zero refined sugar, 21 vitamins",
        "known_claims": ["clean protein", "100% natural", "zero maltodextrin", "high protein growth"],
        "keywords": ["health drink", "bournvita alternative", "horlicks alternative", "gritzo", "gritzo supermilk", "protein drink"],
        "price_inr": 549,
        "price_usd": 7.99,
    },
    {
        "id": "cadbury_bournvita_nutrition_drink",
        "name": "Cadbury Bournvita Nutrition Health Drink",
        "brand": "Cadbury",
        "code": "8901233012345",
        "image_url": "https://images.openfoodfacts.org/images/products/890/123/301/2345/front_en.11.400.jpg",
        "categories": "Beverages, Nutritional drinks, Malt drinks, Health drinks",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Malt Extract (44%), Sugar (37%), Cocoa Solids, Milk Solids, Liquid Glucose, Emulsifiers (322, 471), Raising Agent (500ii), Vitamins and Minerals.",
        "sugars_100g": 37.0,
        "fat_100g": 2.0,
        "saturated_fat_100g": 1.0,
        "proteins_100g": 7.0,
        "fiber_100g": 1.5,
        "energy_kcal_100g": 385,
        "additives_count": 5,
        "nutriscore_grade": "d",
        "labels": "immunity health drink, strong bones, active mind",
        "known_claims": ["boosts immunity", "strong bones", "active mind", "inner strength"],
        "keywords": ["bournvita", "cadbury bournvita", "health drink", "malt drink", "horlicks", "complan"],
        "price_inr": 240,
        "price_usd": 3.50,
    },

    # -------------------------------------------------------------
    # 15. STAPLES, MILLETS & FLOUR
    # -------------------------------------------------------------
    {
        "id": "aashirvaad_millet_atta",
        "name": "Aashirvaad Nature's Superfoods Multi-Millet Atta",
        "brand": "Aashirvaad",
        "code": "8901725012345",
        "image_url": "https://images.openfoodfacts.org/images/products/890/172/501/2345/front_en.9.400.jpg",
        "categories": "Plant-based foods, Cereals, Flours, Atta, Millet flours",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Multi-Millet Flour Blend (Jowar, Bajra, Ragi, Navane, Quinoa). High fiber, gluten-free blend, 100% natural.",
        "sugars_100g": 1.2,
        "fat_100g": 3.0,
        "saturated_fat_100g": 0.6,
        "proteins_100g": 12.0,
        "fiber_100g": 11.5,
        "energy_kcal_100g": 355,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% millets, high fibre, rich in minerals, gluten free blend",
        "known_claims": ["100% millets", "high fibre", "rich in minerals", "superfoods nutrition"],
        "keywords": ["millet atta", "aashirvaad atta", "ragi atta", "jowar atta", "multigrain atta", "atta", "flour"],
        "price_inr": 165,
        "price_usd": 2.49,
    },
    {
        "id": "true_elements_organic_quinoa",
        "name": "True Elements 100% Organic Raw White Quinoa",
        "brand": "True Elements",
        "code": "8906089015555",
        "image_url": "https://images.openfoodfacts.org/images/products/890/608/901/5555/front_en.4.400.jpg",
        "categories": "Plant-based foods, Cereals, Grains, Quinoa",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "100% Certified Organic White Quinoa. Naturally gluten-free complete protein source.",
        "sugars_100g": 0.5,
        "fat_100g": 6.0,
        "saturated_fat_100g": 0.7,
        "proteins_100g": 14.0,
        "fiber_100g": 10.0,
        "energy_kcal_100g": 368,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% organic, complete plant protein, gluten free, high fibre",
        "known_claims": ["100% organic", "complete plant protein", "gluten free", "high fibre"],
        "keywords": ["quinoa", "organic quinoa", "true elements quinoa", "brown rice", "healthy grain"],
        "price_inr": 260,
        "price_usd": 3.99,
    },

    # -------------------------------------------------------------
    # 17. COFFEE, ICED COFFEE & COLD BREW
    # -------------------------------------------------------------
    {
        "id": "sleepy_owl_cold_brew_classic",
        "name": "Sleepy Owl Classic Cold Brew Coffee (Ready to Drink)",
        "brand": "Sleepy Owl",
        "code": "8908012345678",
        "image_url": "https://images.openfoodfacts.org/images/products/890/801/234/5678/front_en.3.400.jpg",
        "categories": "Beverages, Coffees, Iced coffees, Cold brew coffee",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "100% Arabica Coffee Beans, Purified Water. Cold brewed for 18 hours. Zero added sugar, zero preservatives, zero calories.",
        "sugars_100g": 0.0,
        "fat_100g": 0.0,
        "saturated_fat_100g": 0.0,
        "proteins_100g": 0.2,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 2,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "100% arabica, cold brew coffee, zero sugar, no preservatives",
        "known_claims": ["100% arabica", "zero sugar", "no preservatives", "cold brewed 18 hours", "zero calories"],
        "keywords": ["iced coffee", "cold brew", "cold coffee", "sleepy owl", "coffee", "arabica coffee", "black coffee"],
        "price_inr": 120,
        "price_usd": 1.80,
    },
    {
        "id": "blue_tokai_cold_brew_can",
        "name": "Blue Tokai Specialty Cold Brew Coffee (Unsweetened)",
        "brand": "Blue Tokai",
        "code": "8908019876543",
        "image_url": "https://images.openfoodfacts.org/images/products/890/801/987/6543/front_en.5.400.jpg",
        "categories": "Beverages, Coffees, Iced coffees, Cold brew coffee, Specialty coffee",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Single Estate 100% Arabica Specialty Coffee, RO Filtered Water. Zero sugar, zero additives.",
        "sugars_100g": 0.0,
        "fat_100g": 0.0,
        "saturated_fat_100g": 0.0,
        "proteins_100g": 0.3,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 3,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "specialty coffee, 100% arabica, single estate, zero sugar",
        "known_claims": ["specialty coffee", "100% arabica", "single estate", "zero sugar", "pure cold brew"],
        "keywords": ["cold brew", "iced coffee", "blue tokai", "specialty coffee", "black coffee", "cold coffee"],
        "price_inr": 135,
        "price_usd": 1.99,
    },
    {
        "id": "nescafe_classic_cold_coffee_can",
        "name": "Nescafé Cold Coffee Chilled Can (Ready to Drink)",
        "brand": "Nescafe",
        "code": "8901058852999",
        "image_url": "https://images.openfoodfacts.org/images/products/890/105/885/2999/front_en.11.400.jpg",
        "categories": "Beverages, Coffees, Iced coffees, Milk coffee",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Toned Milk (85%), Sugar (9.8%), Coffee (1.2%), Acidity Regulator (INS 339ii), Stabilizer (INS 407).",
        "sugars_100g": 9.8,
        "fat_100g": 1.8,
        "saturated_fat_100g": 1.1,
        "proteins_100g": 2.8,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 75,
        "additives_count": 2,
        "nutriscore_grade": "c",
        "labels": "chilled cold coffee, rich coffee taste",
        "known_claims": ["rich coffee taste", "refreshing cold coffee"],
        "keywords": ["nescafe cold coffee", "iced coffee", "cold coffee", "nescafe", "can coffee", "milk coffee"],
        "price_inr": 50,
        "price_usd": 0.75,
    },
    {
        "id": "continental_xtra_instant_coffee",
        "name": "Continental Xtra Pure South Indian Instant Coffee",
        "brand": "Continental",
        "code": "8906012349999",
        "image_url": "https://images.openfoodfacts.org/images/products/890/601/234/9999/front_en.4.400.jpg",
        "categories": "Beverages, Coffees, Instant coffees",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Coffee (70%), Chicory (30%). Zero added sugar, zero artificial flavours.",
        "sugars_100g": 0.0,
        "fat_100g": 0.0,
        "saturated_fat_100g": 0.0,
        "proteins_100g": 0.5,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 5,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "rich aroma, south indian blend, zero sugar",
        "known_claims": ["rich aroma", "strong blend", "zero sugar"],
        "keywords": ["instant coffee", "continental coffee", "coffee powder", "filter coffee", "coffee"],
        "price_inr": 190,
        "price_usd": 2.75,
    },
    {
        "id": "sleepy_owl_sweet_iced_coffee",
        "name": "Sleepy Owl Sweet Iced Coffee (Lightly Sweetened Real Milk)",
        "brand": "Sleepy Owl",
        "code": "8908012345999",
        "image_url": "https://images.openfoodfacts.org/images/products/890/801/234/5999/front_en.6.400.jpg",
        "categories": "Beverages, Coffees, Iced coffees, Cold coffee, Sweet coffee",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Single Estate Arabica Coffee (60%), Full Cream Milk (35%), Raw Khandsari Cane Sugar (5%). Zero preservatives, zero artificial additives.",
        "sugars_100g": 4.8,
        "fat_100g": 1.5,
        "saturated_fat_100g": 0.9,
        "proteins_100g": 2.5,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 52,
        "additives_count": 0,
        "nutriscore_grade": "b",
        "labels": "lightly sweetened, real milk, no preservatives, arabica coffee",
        "known_claims": ["lightly sweetened", "real milk", "no preservatives", "100% arabica", "zero artificial flavours"],
        "keywords": ["sweet iced coffee", "iced coffee sweet", "sleepy owl sweet coffee", "cold coffee sweet", "sweet coffee", "iced coffee", "sweetened cold brew"],
        "price_inr": 125,
        "price_usd": 1.85,
    },
    {
        "id": "raw_pressery_iced_coffee_dates",
        "name": "Raw Pressery Iced Coffee (Dairy-Free & Sweetened with Dates)",
        "brand": "Raw Pressery",
        "code": "8906076123456",
        "image_url": "https://images.openfoodfacts.org/images/products/890/607/612/3456/front_en.8.400.jpg",
        "categories": "Beverages, Coffees, Iced coffees, Plant milk coffee, Sweet coffee",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Cold Brew Arabica Coffee (65%), Almond Milk (Almonds 10%), Dates Puree (6%), Sea Salt. Zero added refined sugar, zero preservatives.",
        "sugars_100g": 4.2,
        "fat_100g": 2.0,
        "saturated_fat_100g": 0.2,
        "proteins_100g": 2.2,
        "fiber_100g": 1.1,
        "energy_kcal_100g": 48,
        "additives_count": 0,
        "nutriscore_grade": "a",
        "labels": "dairy free, sweetened with dates, no refined sugar, cold brew iced coffee",
        "known_claims": ["sweetened with dates", "no refined sugar", "dairy free", "zero preservatives", "100% clean"],
        "keywords": ["sweet iced coffee", "iced coffee sweet", "raw pressery coffee", "almond iced coffee", "dates sweetened coffee", "iced coffee", "sweet coffee"],
        "price_inr": 120,
        "price_usd": 1.75,
    },
    {
        "id": "blue_tokai_mocha_cold_coffee",
        "name": "Blue Tokai Iced Mocha Specialty Cold Coffee",
        "brand": "Blue Tokai",
        "code": "8908019876999",
        "image_url": "https://images.openfoodfacts.org/images/products/890/801/987/6999/front_en.7.400.jpg",
        "categories": "Beverages, Coffees, Iced coffees, Mocha, Sweet coffee",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Specialty Arabica Cold Brew Coffee (55%), Toned Milk, Single Origin Dark Cocoa, Unrefined Cane Sugar (4.9%).",
        "sugars_100g": 4.9,
        "fat_100g": 1.2,
        "saturated_fat_100g": 0.7,
        "proteins_100g": 2.6,
        "fiber_100g": 0.8,
        "energy_kcal_100g": 50,
        "additives_count": 0,
        "nutriscore_grade": "b",
        "labels": "specialty iced coffee, dark mocha, unrefined sugar, zero preservatives",
        "known_claims": ["specialty iced coffee", "dark mocha", "unrefined cane sugar", "zero preservatives"],
        "keywords": ["sweet iced coffee", "mocha cold coffee", "iced coffee sweet", "blue tokai mocha", "iced mocha", "cold coffee", "sweet coffee"],
        "price_inr": 145,
        "price_usd": 2.10,
    },
    # -------------------------------------------------------------
    # SECTION 18: DAIRY BUTTER & TABLE SPREADS
    # -------------------------------------------------------------
    {
        "id": "amul_pasteurized_butter",
        "name": "Amul Pasteurized Butter",
        "brand": "Amul",
        "code": "8901262010054",
        "image_url": "https://images.openfoodfacts.org/images/products/890/126/201/0054/front_en.10.400.jpg",
        "categories": "Dairies, Fats, Spreadable fats, Animal fats, Milkfat, Butters, Salted butters, Pasteurized butters",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Butter (Milk Fat 80%), Common Salt, Permitted Natural Colour (INS 160a(i) / Annatto).",
        "sugars_100g": 0.0,
        "fat_100g": 80.0,
        "saturated_fat_100g": 51.0,
        "proteins_100g": 0.5,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 722,
        "additives_count": 1,
        "nutriscore_grade": "d",
        "labels": "pasteurized salted butter, utterly butterly delicious",
        "known_claims": ["pasteurized butter", "made from fresh milk fat", "utterly butterly delicious"],
        "keywords": ["amul butter", "pasteurized butter", "salted butter", "amul pasteurized butter", "table butter", "butter"],
        "price_inr": 58,
        "price_usd": 0.90,
    },
    {
        "id": "amul_unsalted_butter",
        "name": "Amul White Unsalted Butter",
        "brand": "Amul",
        "code": "8901262010153",
        "image_url": "https://images.openfoodfacts.org/images/products/890/126/201/0153/front_en.10.400.jpg",
        "categories": "Dairies, Fats, Spreadable fats, Animal fats, Milkfat, Butters, Unsalted butters, White butter",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Pure Milk Fat (Minimum 82%). Zero added salt, zero preservatives, zero artificial color.",
        "sugars_100g": 0.0,
        "fat_100g": 82.0,
        "saturated_fat_100g": 52.0,
        "proteins_100g": 0.6,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 740,
        "additives_count": 0,
        "nutriscore_grade": "d",
        "labels": "unsalted butter, pure milk fat, zero salt, zero additives, white butter",
        "known_claims": ["zero added salt", "zero preservatives", "100% pure milk fat", "no artificial color"],
        "keywords": ["amul unsalted butter", "unsalted butter", "amul white butter", "white butter", "pure cow butter", "butter"],
        "price_inr": 60,
        "price_usd": 0.95,
    },
    {
        "id": "tbof_cultured_a2_gir_cow_makhan",
        "name": "Two Brothers Organic Farms Cultured A2 Gir Cow Makhan (White Butter)",
        "brand": "Two Brothers Organic Farms",
        "code": "8906132450123",
        "image_url": "https://images.openfoodfacts.org/images/products/890/613/245/0123/front_en.5.400.jpg",
        "categories": "Dairies, Fats, Spreadable fats, Butters, Cultured butter, A2 makhan, Desi butter, White butter",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Cultured A2 Gir Cow Curd Makkhan (Unsalted). Made from whole A2 milk of free-grazing Gir cows, churned using traditional bilona method. 100% natural, zero additives.",
        "sugars_100g": 0.0,
        "fat_100g": 82.5,
        "saturated_fat_100g": 53.0,
        "proteins_100g": 0.7,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 745,
        "additives_count": 0,
        "nutriscore_grade": "d",
        "labels": "a2 gir cow, cultured makhan, bilona churned, traditional desi butter, zero additives, certified organic",
        "known_claims": ["a2 gir cow milk", "bilona cultured makhan", "100% natural", "zero additives", "zero preservatives"],
        "keywords": ["two brothers makhan", "cultured a2 butter", "a2 cow butter", "two brothers butter", "makhan", "white makhan", "desi makhan", "cultured butter", "butter"],
        "price_inr": 550,
        "price_usd": 7.50,
    },
    {
        "id": "country_delight_cow_butter",
        "name": "Country Delight Natural Cow Butter",
        "brand": "Country Delight",
        "code": "8908009876543",
        "image_url": "https://images.openfoodfacts.org/images/products/890/800/987/6543/front_en.5.400.jpg",
        "categories": "Dairies, Fats, Spreadable fats, Butters, Cow butter, Table butter",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Pasteurized Cow Milk Fat (80%), Salt (less than 1%).",
        "sugars_100g": 0.0,
        "fat_100g": 80.5,
        "saturated_fat_100g": 51.0,
        "proteins_100g": 0.6,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 725,
        "additives_count": 0,
        "nutriscore_grade": "d",
        "labels": "natural cow butter, no artificial colours, minimal salt",
        "known_claims": ["natural cow butter", "no artificial colours", "100% cow milk"],
        "keywords": ["country delight butter", "cow butter", "natural butter", "table butter", "butter"],
        "price_inr": 85,
        "price_usd": 1.25,
    },
    {
        "id": "milky_mist_unsalted_butter",
        "name": "Milky Mist Table Butter Unsalted",
        "brand": "Milky Mist",
        "code": "8904083500245",
        "image_url": "https://images.openfoodfacts.org/images/products/890/408/350/0245/front_en.5.400.jpg",
        "categories": "Dairies, Fats, Spreadable fats, Butters, Unsalted butters",
        "countries": "India",
        "is_available_in_india": True,
        "ingredients_text": "Pasteurized Cream from Cow & Buffalo Milk (Fat 82%). Zero added salt, zero color.",
        "sugars_100g": 0.0,
        "fat_100g": 82.0,
        "saturated_fat_100g": 52.5,
        "proteins_100g": 0.5,
        "fiber_100g": 0.0,
        "energy_kcal_100g": 738,
        "additives_count": 0,
        "nutriscore_grade": "d",
        "labels": "unsalted butter, pure pasteurized cream, zero additives",
        "known_claims": ["zero added salt", "zero preservatives", "100% pure cream"],
        "keywords": ["milky mist butter", "milky mist unsalted butter", "unsalted butter", "table butter", "butter"],
        "price_inr": 75,
        "price_usd": 1.15,
    },
]


def _normalize_str(s: str) -> str:
    return re.sub(r"[-—|:;,/()]+", " ", s.lower()).strip()


def find_curated_product(query: str, country: str = "india") -> dict | None:
    """
    Searches the curated Indian FMCG & supplements database for a matching product.
    Supports fuzzy name, brand, and keyword matches.
    """
    if not query or not query.strip():
        return None

    clean_q = _normalize_str(query)
    q_tokens = clean_q.split()

    # Pass 1: Exact keyword / ID match
    for item in CURATED_FOOD_DATABASE:
        if clean_q == item["id"] or clean_q == item["name"].lower():
            return _format_curated_evidence(item, country=country)
        if any(clean_q == kw.lower() for kw in item.get("keywords", [])):
            return _format_curated_evidence(item, country=country)

    # Pass 2: Substring or high token overlap
    best_item = None
    best_score = 0.0

    for item in CURATED_FOOD_DATABASE:
        item_text = f"{item['brand']} {item['name']} {' '.join(item.get('keywords', []))}".lower()
        matched_tokens = sum(1 for t in q_tokens if t in item_text)
        token_ratio = matched_tokens / len(q_tokens) if q_tokens else 0

        seq_ratio = difflib.SequenceMatcher(None, clean_q, item["name"].lower()).ratio()
        score = (token_ratio * 0.7) + (seq_ratio * 0.3)

        if score > best_score and score >= 0.50:
            best_score = score
            best_item = item

    if best_item:
        return _format_curated_evidence(best_item, country=country)

    return None


def search_curated_category(category_domain: str, query: str = "", country: str = "india") -> list[dict]:
    """
    Searches the curated database for products matching a category domain or search query.
    """
    results = []
    clean_q = _normalize_str(f"{category_domain} {query}")
    terms = clean_q.split()

    for item in CURATED_FOOD_DATABASE:
        item_cat = f"{item['categories']} {' '.join(item.get('keywords', []))}".lower()
        if any(term in item_cat for term in terms):
            results.append(_format_curated_evidence(item, country=country))

    return results



CATEGORY_IMAGE_MAP = {
    # Genuine product packaging only (bottles, containers, tubs) - ZERO cooked dishes/bowls
    "soy sauce": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Soy_sauce_in_bottles.jpg/640px-Soy_sauce_in_bottles.jpg",
    "soya sauce": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Soy_sauce_in_bottles.jpg/640px-Soy_sauce_in_bottles.jpg",
    "shoyu": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Soy_sauce_in_bottles.jpg/640px-Soy_sauce_in_bottles.jpg",
    "tamari": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Soy_sauce_in_bottles.jpg/640px-Soy_sauce_in_bottles.jpg",
    "balsamic": "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=600&q=80",
    "apple cider vinegar": "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=600&q=80",
    "vinegar": "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=600&q=80",
    "cold brew": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80",
    "coffee": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80",
    "olive": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80",
    "oil": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80",
    "whey": "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&w=600&q=80",
    "protein": "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&w=600&q=80",
}

# Dish photo blacklist - reject any cooked meals, bowls, or plates of food
DISH_PHOTO_BLACKLIST = [
    "photo-1612927601601",  # noodle/ramen bowl with egg
    "photo-1551462147",     # cooked pasta plate
    "photo-1568271679",     # peanut toast
    "photo-1549007994",     # spread toast
    "photo-1586201375",     # oat bowl
    "photo-1517093157",     # muesli bowl
    "photo-1521483451",     # cereal bowl
    "photo-1579722821",     # protein shake glass
    "photo-1589985270",     # butter block
    "photo-1558961363",     # cookies tray
    "photo-1488477181",     # yogurt bowl
    "photo-1550583724",     # milk glass
    "photo-1509440159",     # flour bread
    "photo-1607623814",     # salsa bowl
    "photo-1546069901",     # salad bowl
    "photo-1566478989",     # snack bowl
]


def resolve_curated_image(item: dict) -> str:
    raw_img = item.get("image_url", "")
    if raw_img:
        # Check if raw_img is a blacklisted dish photo
        if any(bad in raw_img for bad in DISH_PHOTO_BLACKLIST):
            raw_img = ""
        else:
            return raw_img
    text = (item.get("name", "") + " " + item.get("categories", "") + " " + item.get("brand", "")).lower()
    for kw, url in CATEGORY_IMAGE_MAP.items():
        if kw in text:
            return url
    return raw_img or ""


def _format_curated_evidence(item: dict, country: str = "India") -> dict:
    is_india = (country or "").lower() in ["india", "in", "en:india"]
    query_name = item.get("name", "")
    brand = item.get("brand", "")
    encoded = urllib.parse.quote_plus(f"{brand} {query_name}".strip())

    buy_links = []
    if is_india:
        buy_links.append({
            "platform": "Amazon India",
            "icon": "🛒",
            "url": f"https://www.amazon.in/s?k={encoded}",
            "color": "#f59e0b",
        })
        buy_links.append({
            "platform": "Blinkit",
            "icon": "⚡",
            "url": f"https://blinkit.com/s/?q={encoded}",
            "color": "#eab308",
        })
        buy_links.append({
            "platform": "Google Shopping",
            "icon": "🛍️",
            "url": f"https://www.google.com/search?tbm=shop&q={encoded}",
            "color": "#38bdf8",
        })
    else:
        buy_links.append({
            "platform": "Amazon",
            "icon": "🛒",
            "url": f"https://www.amazon.com/s?k={encoded}",
            "color": "#f59e0b",
        })
        buy_links.append({
            "platform": "Google Shopping",
            "icon": "🛍️",
            "url": f"https://www.google.com/search?tbm=shop&q={encoded}",
            "color": "#38bdf8",
        })

    code = item.get("code", "")
    price_inr = item.get("price_inr", 299)
    price_usd = item.get("price_usd", 4.99)
    formatted_price = f"₹{price_inr}" if is_india else f"${price_usd:.2f}"

    return {
        "name": item["name"],
        "brand": item.get("brand", "Unknown"),
        "code": code,
        "image_url": resolve_curated_image(item),
        "countries": item.get("countries", "India"),
        "is_available_in_india": item.get("is_available_in_india", True),
        "source": "curated_fssai_database",
        "buy_links": buy_links,
        "price_inr": price_inr,
        "price_usd": price_usd,
        "formatted_price": formatted_price,
        "price_is_estimate": False,
        "ingredients_text": item.get("ingredients_text", ""),
        "sugars_100g": round(float(item["sugars_100g"]), 1) if item.get("sugars_100g") is not None else None,
        "fat_100g": round(float(item["fat_100g"]), 1) if item.get("fat_100g") is not None else None,
        "saturated_fat_100g": round(float(item["saturated_fat_100g"]), 1) if item.get("saturated_fat_100g") is not None else None,
        "proteins_100g": round(float(item["proteins_100g"]), 1) if item.get("proteins_100g") is not None else None,
        "fiber_100g": round(float(item["fiber_100g"]), 1) if item.get("fiber_100g") is not None else None,
        "energy_kcal_100g": item.get("energy_kcal_100g"),
        "additives_count": item.get("additives_count", 0),
        "nutriscore_grade": item.get("nutriscore_grade"),
        "categories": item.get("categories", ""),
        "generic_name": item.get("name", ""),
        "labels": item.get("labels", ""),
        "known_claims": item.get("known_claims", []),
    }
